# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.5.x version
  - 5.5
  # hhvm
  #- hhvm

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
before_script:
  - composer install --no-interaction
  - mkdir -p build/logs

script:
  - vendor/phpunit/phpunit/phpunit --configuration phpunit.travis.xml --coverage-clover build/logs/clover.xml test

after_success:
    - php vendor/bin/coveralls -v

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "ashley@zf4.biz"

